import os
from typing import List
import parmed as pmd
from collections import defaultdict, Counter
import subprocess

class LammpsFinaliser:
    """
    Class to finalise the LAMMPS simulation files by writing the pair_coeffs file and the input script.
    """
    def __init__(self, cif_name: str, output_dir: str, replicate_factors: List[int] = None) -> None:
        self.cif_name = cif_name
        self.output_dir = output_dir
        self.replicate_factors = replicate_factors
        self.atom_types = []

    def get_atom_ids(self) -> List[str]:
        """
        Function to get the atom types from the AMBER prmtop file and LAMMPS data file, and map them together to be able
        to write the pair_coeffs later on with the correct atom types. The output is a list of strings, each containing
        the atom index and the corresponding GAFF atom type.

        :return: List of strings with atom index and GAFF atom type.
        """
        prmtop_name = f"system.prmtop"
        prmtop_path = os.path.join(self.output_dir, prmtop_name)

        data_name = f"data_{self.cif_name}.txt"
        data_path = os.path.join(self.output_dir, data_name)

        # First, get the GAFF atom types from the prmtop file provided by Amber
        prm_file = pmd.load_file(prmtop_path)
        gaff = []
        
        for atoms in prm_file.atoms:
            if atoms.atom_type:
                gaff.append(atoms.atom_type.name)
            else:
                gaff.append(atoms.type)

        cleaned_gaff = []
        for x in gaff:
            cleaned_gaff.append(str(x).strip())
        gaff = cleaned_gaff

        # Get the numeric atom types from the LAMMPS data file
        types = []
        with open(data_path) as file:

            # Find the Atoms header
            for line in file:
                if line.strip().lower().startswith("atoms"):
                    break

            # In case there are blank lines after header, skip them
            for line in file:
                if line.strip():
                    break

            # While in the Atom block, extract atom types, and stop reading when a blank line is found
            while line and line.strip():
                parts = line.split()
                if len(parts) >= 3:
                    types.append(int(float(parts[2])))  # column 3 = atom type
                line = file.readline()

        atom_GAFF_types = defaultdict(list)
        
        for type, name in zip(types, gaff[:len(types)]):
            atom_GAFF_types[type].append(name)

        # For each unique atom type, find the corresponding GAFF type. Use the most common GAFF type if multiple map to
        # the same atom type. Technically shouldn't happen, but actually does in some cases.
        self.atom_types = []
        
        for type in sorted(atom_GAFF_types):
            counts = Counter(atom_GAFF_types[type])
            most_common_type = counts.most_common(1)[0][0]
            entry = f"{type} {most_common_type}"
            self.atom_types.append(entry)

        return self.atom_types

    def extract_and_modify_pair_coeff_block(self) -> List[str]:
        """
        Extract the pair_coeff block from the extra_<cif_name>.txt file and modify it to include the LJ header.

        :return: List of strings containing the modified pair_coeff block.
        """
        filename = f"extra_{self.cif_name}.txt"
        data_path = os.path.join(self.output_dir, filename)

        with open(data_path, 'r') as file:
            lines = file.readlines()

        modified_block = []
        in_block = False

        for line in lines:
            stripped = line.strip()

            if stripped.startswith("pair_coeff"):
                in_block = True
                parts = stripped.split()
                # Expected format: pair_coeff i j value1 value2
                # Insert lj/cut/coul/long after the two indices
                if len(parts) >= 4:
                    modified_line = f"{parts[0]} {parts[1]} {parts[2]} lj/cut/coul/long {' '.join(parts[3:])}"
                    modified_block.append(modified_line)
                else:
                    modified_block.append(stripped)
            elif in_block and not stripped.startswith("pair_coeff"):
                # Once we exit the pair_coeff section, stop collecting
                break
        return modified_block

    # snippet highlighting the modified functions inside lammps_finaliser.py

    def extract_topology_styles(self) -> dict:
        """
        Reads the extra_{cif_name}.txt file generated by InterMol to determine exactly
        which bond, angle, dihedral, and improper styles are present in the data file.

        :return: A dictionary mapping topology variables to their respective styles.
        """
        filename = f"extra_{self.cif_name}.txt"
        data_path = os.path.join(self.output_dir, filename)

        styles = {
            "bond_style": None,
            "angle_style": None,
            "dihedral_style": None,
            "improper_style": None,
            "special_bonds": None
        }

        if os.path.exists(data_path):
            with open(data_path, 'r') as file:
                for line in file:
                    stripped = line.strip()
                    if stripped.startswith("bond_style"):
                        styles["bond_style"] = stripped
                    elif stripped.startswith("angle_style"):
                        styles["angle_style"] = stripped
                    elif stripped.startswith("dihedral_style"):
                        styles["dihedral_style"] = stripped
                    elif stripped.startswith("improper_style"):
                        styles["improper_style"] = stripped
                    elif stripped.startswith("special_bonds"):
                        styles["special_bonds"] = stripped

        return styles
        
    def coeffs_writer(self, organic_pair_coeffs_block: List[str]) -> str:
        """
        Write the pair_coeffs file for LAMMPS, combining the organic-organic pairs from Amber (provided) with the
        inorganic-inorganic and organic-inorganic pairs as gathered from literature (Buckingham and LJ parameters).

        :param organic_pair_coeffs_block: List of strings containing the pair_coeff block that Amber provided.
        :return: Path to the written pair_coeffs file.
        """
        BH = {
            #===========================#
            # Inorganic–Inorganic pairs #
            #===========================#
            "PB,PB": [70359906.62970, 0.131258, 0.00],
            "PB,I": [103496.13301, 0.321737, 0.00],
            "I,PB": [103496.13301, 0.321737, 0.00],
            "I,I": [22793.33858, 0.482217, 696.94954],

            #==========================#
            # Pb–C pairs (all C types) #
            #==========================#
            "PB,c": [32690390.93800, 0.150947, 0.00],
            "PB,c1": [32690390.93800, 0.150947, 0.00],
            "PB,c2": [32690390.93800, 0.150947, 0.00],
            "PB,c3": [32690390.93800, 0.150947, 0.00],
            "PB,c5": [32690390.93800, 0.150947, 0.00],
            "PB,ca": [32690390.93800, 0.150947, 0.00],
            "PB,cp": [32690390.93800, 0.150947, 0.00],
            "PB,cq": [32690390.93800, 0.150947, 0.00],
            "PB,cc": [32690390.93800, 0.150947, 0.00],
            "PB,cd": [32690390.93800, 0.150947, 0.00],
            "PB,ce": [32690390.93800, 0.150947, 0.00],
            "PB,cf": [32690390.93800, 0.150947, 0.00],
            "PB,cg": [32690390.93800, 0.150947, 0.00],
            "PB,ch": [32690390.93800, 0.150947, 0.00],
            "PB,cx": [32690390.93800, 0.150947, 0.00],
            "PB,cy": [32690390.93800, 0.150947, 0.00],
            "PB,cu": [32690390.93800, 0.150947, 0.00],
            "PB,cv": [32690390.93800, 0.150947, 0.00],
            "PB,cz": [32690390.93800, 0.150947, 0.00],
            "PB,c6": [32690390.93800, 0.150947, 0.00],

            #==========================#
            # Pb–N pairs (all N types) #
            #==========================#
            "PB,n": [32690390.93800, 0.150947, 0.00],
            "PB,n1": [32690390.93800, 0.150947, 0.00],
            "PB,n2": [32690390.93800, 0.150947, 0.00],
            "PB,n3": [32690390.93800, 0.150947, 0.00],
            "PB,n4": [32690390.93800, 0.150947, 0.00],
            "PB,na": [32690390.93800, 0.150947, 0.00],
            "PB,nb": [32690390.93800, 0.150947, 0.00],
            "PB,nc": [32690390.93800, 0.150947, 0.00],
            "PB,nd": [32690390.93800, 0.150947, 0.00],
            "PB,ne": [32690390.93800, 0.150947, 0.00],
            "PB,nf": [32690390.93800, 0.150947, 0.00],
            "PB,nh": [32690390.93800, 0.150947, 0.00],
            "PB,no": [32690390.93800, 0.150947, 0.00],
            "PB,nz": [32690390.93800, 0.150947, 0.00],
            "PB,nv": [32690390.93800, 0.150947, 0.00],
            "PB,nx": [32690390.93800, 0.150947, 0.00],
            "PB,ny": [32690390.93800, 0.150947, 0.00],

            #==========================#
            # Pb–O pairs (all O types) #
            #==========================#
            "PB,o": [32690390.93800, 0.150947, 0.00],
            "PB,oh": [32690390.93800, 0.150947, 0.00],
            "PB,os": [32690390.93800, 0.150947, 0.00],
            "PB,ow": [32690390.93800, 0.150947, 0.00],

            #=========================#
            # I–C pairs (all C types) #
            #=========================#
            "I,c": [112936.71421, 0.342426, 0.00],
            "I,c1": [112936.71421, 0.342426, 0.00],
            "I,c2": [112936.71421, 0.342426, 0.00],
            "I,c3": [112936.71421, 0.342426, 0.00],
            "I,c5": [112936.71421, 0.342426, 0.00],
            "I,ca": [112936.71421, 0.342426, 0.00],
            "I,cp": [112936.71421, 0.342426, 0.00],
            "I,cq": [112936.71421, 0.342426, 0.00],
            "I,cc": [112936.71421, 0.342426, 0.00],
            "I,cd": [112936.71421, 0.342426, 0.00],
            "I,ce": [112936.71421, 0.342426, 0.00],
            "I,cf": [112936.71421, 0.342426, 0.00],
            "I,cg": [112936.71421, 0.342426, 0.00],
            "I,ch": [112936.71421, 0.342426, 0.00],
            "I,cx": [112936.71421, 0.342426, 0.00],
            "I,cy": [112936.71421, 0.342426, 0.00],
            "I,cu": [112936.71421, 0.342426, 0.00],
            "I,cv": [112936.71421, 0.342426, 0.00],
            "I,cz": [112936.71421, 0.342426, 0.00],
            "I,c6": [112936.71421, 0.342426, 0.00],

            #=========================#
            # I–N pairs (all N types) #
            #=========================#
            "I,n": [112936.71421, 0.342426, 0.00],
            "I,n1": [112936.71421, 0.342426, 0.00],
            "I,n2": [112936.71421, 0.342426, 0.00],
            "I,n3": [112936.71421, 0.342426, 0.00],
            "I,n4": [112936.71421, 0.342426, 0.00],
            "I,na": [112936.71421, 0.342426, 0.00],
            "I,nb": [112936.71421, 0.342426, 0.00],
            "I,nc": [112936.71421, 0.342426, 0.00],
            "I,nd": [112936.71421, 0.342426, 0.00],
            "I,ne": [112936.71421, 0.342426, 0.00],
            "I,nf": [112936.71421, 0.342426, 0.00],
            "I,nh": [112936.71421, 0.342426, 0.00],
            "I,no": [112936.71421, 0.342426, 0.00],
            "I,nz": [112936.71421, 0.342426, 0.00],
            "I,nv": [112936.71421, 0.342426, 0.00],
            "I,nx": [112936.71421, 0.342426, 0.00],
            "I,ny": [112936.71421, 0.342426, 0.00],

            #=========================#
            # I–O pairs (all O types) #
            #=========================#
            "I,o": [112936.71421, 0.342426, 0.00],
            "I,oh": [112936.71421, 0.342426, 0.00],
            "I,os": [112936.71421, 0.342426, 0.00],
            "I,ow": [112936.71421, 0.342426, 0.00],
        }

        LJ = {
            #======================#
            #      Pb-H types      #
            #======================#
            "PB,h1": [0.01400, 2.70999],
            "PB,h2": [0.01400, 2.70999],
            "PB,h3": [0.01400, 2.70999],
            "PB,h4": [0.01400, 2.70999],
            "PB,h5": [0.01400, 2.70999],
            "PB,ha": [0.01400, 2.70999],
            "PB,hc": [0.01400, 2.70999],
            "PB,hx": [0.01400, 2.70999],
            "PB,hn": [0.01400, 2.26454],
            "PB,ho": [0.01400, 2.26454],
            "P,hp": [0.01400, 2.26454],
            "PB,hs": [0.01400, 2.26454],
            "PB,hw": [0.01400, 2.26454],

            #=====================#
            #      I-H types      #
            #=====================#
            "I,h1": [0.05740, 3.1000],
            "I,h2": [0.05740, 3.1000],
            "I,h3": [0.05740, 3.1000],
            "I,h4": [0.05740, 3.1000],
            "I,h5": [0.05740, 3.1000],
            "I,ha": [0.05740, 3.1000],
            "I,hc": [0.05740, 3.1000],
            "I,hx": [0.05740, 3.1000],
            "I,hn": [0.05740, 2.7500],
            "I,ho": [0.05740, 2.7500],
            "I,hp": [0.05740, 2.7500],
            "I,hs": [0.05740, 2.7500],
            "I,hw": [0.05740, 2.7500],
        }

        filename = f"coeffs_{self.cif_name}.txt"
        output_path = os.path.join(self.output_dir, filename)

        lines = ["# Organic-Organic (LJ) --> Provided by Amber\n"]
        for line in organic_pair_coeffs_block[:-2]:  # Skip the last two lines; these are inorganic atoms
            lines.append(f"{line}\n")

        lines.append("\n# Inorganic-Inorganic (BH) --> Papers\n")

        inorg_idx = []
        # Take the last two atom types (they are always inorganics)
        inorganic_atoms = self.atom_types[-2:]

        for entry in inorganic_atoms:
            index, atom_type = entry.split()
            inorg_idx.append(index)

            # Symmetric lookup in BH dict (e.g. PB,PB)
            BH_lookup = f"{atom_type},{atom_type}"
            if BH_lookup not in BH:
                BH_lookup = f"{atom_type},{atom_type}"

            BH_values = BH[BH_lookup]
            A, rho, C = BH_values

            lines.append(f"pair_coeff {index} {index} buck/coul/long  {A}   {rho}   {C}\n")

        # Cross-term between the two inorganic atom types
        atom_type_1 = self.atom_types[-2].split()[1]
        atom_type_2 = self.atom_types[-1].split()[1]

        # Lookup both atoms in BH dict; try both orders (e.g. PB,I and I,PB should return same results)
        BH_lookup = f"{atom_type_1},{atom_type_2}"
        if BH_lookup not in BH:
            BH_lookup = f"{atom_type_2},{atom_type_1}"
        BH_values = BH[BH_lookup]
        A, rho, C = BH_values

        lines.append(f"pair_coeff {inorg_idx[0]} {inorg_idx[1]} buck/coul/long  {A}   {rho}   {C}\n\n")
        lines.append("# Hydrogen-Inorganic (LJ) --> Papers\n")

        # Get inorganic atom info
        inorganics = self.atom_types[-2:]
        inorg_info = [(entry.split()[0], entry.split()[1]) for entry in inorganics]

        # Get hydrogen atom info
        hydrogens = []
        for entry in self.atom_types:
            parts = entry.split()
            atom_id = parts[0]
            atom_type = parts[1]
            if atom_type.lower().startswith("h"):
                hydrogens.append((atom_id, atom_type))

        # Based on the found hydrogens and inorganics, write the pair coeffs based on the information from the LJ dict
        for h_index, h_type in hydrogens:
            for inorg_index, inorg_type in inorg_info:
                pair_key = f"{inorg_type},{h_type}"
                reverse_key = f"{h_type},{inorg_type}"

                if pair_key in LJ:
                    eps, sigma = LJ[pair_key]
                elif reverse_key in LJ:
                    eps, sigma = LJ[reverse_key]
                else:
                    raise KeyError(f"No LJ parameters found for pair: {inorg_type}-{h_type}")

                # Hydrogen/organic FIRST in output
                lines.append(f"pair_coeff {h_index} {inorg_index} lj/cut/coul/long  {eps}  {sigma}\n")

        # Get organic atom info (all non-hydrogen, non-inorganic)
        lines.append("\n# Organic-Inorganic (BH) --> Papers\n")
        organics = []
        for entry in self.atom_types[:-2]:
            parts = entry.split()
            atom_id = parts[0]
            atom_type = parts[1]
            if not atom_type.lower().startswith("h"):
                organics.append((atom_id, atom_type))

        # Based on the found organics and inorganics, write the pair coeffs based on the information from the BH dict
        for org_index, org_type in organics:
            for inorg_index, inorg_type in inorg_info:
                pair_key = f"{inorg_type},{org_type}"
                reverse_key = f"{org_type},{inorg_type}"

                if pair_key in BH:
                    A, rho, C = BH[pair_key]
                elif reverse_key in BH:
                    A, rho, C = BH[reverse_key]
                else:
                    print(f"Warning: No BH parameters found for pair {inorg_type}-{org_type}")
                    continue

                # Organic FIRST in output
                lines.append(f"pair_coeff {org_index} {inorg_index} buck/coul/long  {A}   {rho}   {C}\n")

        with open(output_path, "w") as file:
            file.writelines(lines)

        print(f"Wrote pair_coeff file: {output_path}")
        return output_path

    def input_writer(self) -> None:
        """
        Write the LAMMPS input script for step-wise compression.
        Tracks the box lengths (lx, ly, lz) continuously during the ENTIRE run 
        (both ramps and plateaus) into a single output file.

        :return: None
        """
        filename = f"input.in"
        data_path = os.path.join(self.output_dir, filename)
        nx, ny, nz = self.replicate_factors
        
        element_dict = {
            'pb': 'Pb', 'sn': 'Sn', 'cs': 'Cs', 'cu': 'Cu',
            'br': 'Br', 'cl': 'Cl', 'i': 'I',
            'c': 'C', 'n': 'N', 'o': 'O', 'h': 'H', 's': 'S'
        }
        
        element_list = []
        for entry in self.atom_types:
            gaff_type = entry.split()[1].lower()
            chosen_element = 'X' 
            for prefix, symbol in element_dict.items():
                if gaff_type.startswith(prefix):
                    chosen_element = symbol
                    break 
            element_list.append(chosen_element)
            
        element_string = " ".join(element_list)
        lines = []

        lines.append("units           real\n")
        lines.append("atom_style      full\n")
        lines.append("boundary        p p p\n\n")
        
        topo_styles = self.extract_topology_styles()
        
        if topo_styles["bond_style"]: lines.append(f"{topo_styles['bond_style']}\n")
        if topo_styles["angle_style"]: lines.append(f"{topo_styles['angle_style']}\n")
        if topo_styles["dihedral_style"]: lines.append(f"{topo_styles['dihedral_style']}\n")
        if topo_styles["improper_style"]: lines.append(f"{topo_styles['improper_style']}\n")
            
        if topo_styles["special_bonds"]:
            lines.append(f"{topo_styles['special_bonds']}\n\n")
        else:
            lines.append("special_bonds   lj 0.0 0.0 0.5 coul 0.0 0.0 0.83333333\n\n")
            
        lines.append(f"read_data       data_{self.cif_name}.txt\n")
        lines.append(f"replicate       {nx} {ny} {nz}\n\n")

        lines.append("pair_style      hybrid lj/cut/coul/long 9.0 buck/coul/long 9.0\n")
        lines.append("pair_modify     mix arithmetic\n")
        lines.append("pair_modify     tail yes\n")
        lines.append("kspace_style    pppm 1.0e-4\n\n")

        lines.append(f"include         coeffs_{self.cif_name}.txt\n\n")
        lines.append("timestep        1.0\n\n")
        
        lines.append("thermo_style    custom step time enthalpy etotal press temp vol lx ly lz\n")
        lines.append("thermo          500\n\n")

        lines.append("# Variables for box dimensions\n")
        lines.append("variable        lx equal lx\n")
        lines.append("variable        ly equal ly\n")
        lines.append("variable        lz equal lz\n\n")

        lines.append("# INITIAL RELAXATION TO PREVENT BOX EXPLOSIONS\n")
        lines.append("minimize        1.0e-4 1.0e-6 1000 10000\n")
        lines.append("velocity        all create 100.0 4540 mom yes dist gaussian\n\n")
        lines.append("fix             1 all nve/limit 0.1\n")
        lines.append("run             10000\n")
        lines.append("unfix           1\n")
        lines.append("reset_timestep  0\n\n")

        lines.append("# trajectory file\n")
        lines.append(f"dump            alltraj all custom 1000 {self.cif_name}_100K_all.lammpstrj id type element x y z xu yu zu vx vy vz\n")
        lines.append(f"dump_modify     alltraj element {element_string}\n\n")

        lines.append("# Continuous box size output for the entire compression process\n")
        lines.append(f"fix             box_output all ave/time 10 100 1000 v_lx v_ly v_lz file {self.cif_name}_box_compression_continuous.txt\n\n")

        pressures = [1000, 2000, 3000, 4000]
        fix_id = 2

        lines.append("# 1 atm equilibration run\n")
        lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso 1.0 1.0 1000.0\n")
        lines.append("run             80000\n")
        lines.append(f"unfix           {fix_id}\n\n")
        
        fix_id += 1
        prev_p = 1.0

        for p in pressures:
            lines.append(f"# {int(prev_p)}-{p} atm ramp\n")
            lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso {float(prev_p)} {float(p)} 1000.0\n")
            lines.append("run             30000\n")
            lines.append(f"unfix           {fix_id}\n\n")
            fix_id += 1
            
            lines.append(f"# {p} atm plateau\n")
            lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso {float(p)} {float(p)} 1000.0\n")
            lines.append("run             50000\n")
            lines.append(f"unfix           {fix_id}\n\n")
            fix_id += 1
            
            prev_p = p
            
        with open(data_path, "w") as file:
            file.writelines(lines)
            
    def save_everything_to_folder(self) -> bool:
        """
        Move all generated simulation files to a dedicated folder for this CIF number. Besides moving the just created
        data, coeffs, and input files, also copy the run.sh script to the folder so that each simulation folder can be
        run independently. If the target folder ends up empty (due to errors), remove it.

        :return: Return True if everything goes well during LAMMPS conversion, otherwise return False.
        """
        cmd = (f"mkdir -p ../../simulation_files\n"
               f"mkdir -p ../../simulation_files/{self.cif_name}\n"
               f"mv -f data_{self.cif_name}.txt ../../simulation_files/{self.cif_name}/data_{self.cif_name}.txt\n"
               f"mv -f coeffs_{self.cif_name}.txt ../../simulation_files/{self.cif_name}/coeffs_{self.cif_name}.txt\n"
               f"mv -f input.in ../../simulation_files/{self.cif_name}/input.in\n"
               f"cp -f ../../run.sh ../../simulation_files/{self.cif_name}/run.sh\n")
        result = subprocess.run(cmd, shell=True, cwd=self.output_dir, capture_output=True, text=True)

        target_dir = os.path.join(os.getcwd(), f"simulation_files", str(self.cif_name))
        if not os.listdir(target_dir):
            print(f"Directory {target_dir} is empty. Removing it and the current folder.")
            os.rmdir(target_dir)
        else:
            print(f"Directory {target_dir} contains files, keeping it.")

        if result.returncode != 0:
            print(f"Error during LAMMPS conversion:\n{result.stderr}")
            return False
        print(result.stdout)
        return True
