# snippet highlighting the modified functions inside lammps_finaliser.py

    def extract_topology_styles(self) -> dict:
        """
        Reads the extra_{cif_name}.txt file generated by InterMol to determine exactly
        which bond, angle, dihedral, and improper styles are present in the data file.

        :return: A dictionary mapping topology variables to their respective styles.
        """
        filename = f"extra_{self.cif_name}.txt"
        data_path = os.path.join(self.output_dir, filename)

        styles = {
            "bond_style": None,
            "angle_style": None,
            "dihedral_style": None,
            "improper_style": None,
            "special_bonds": None
        }

        if os.path.exists(data_path):
            with open(data_path, 'r') as file:
                for line in file:
                    stripped = line.strip()
                    if stripped.startswith("bond_style"):
                        styles["bond_style"] = stripped
                    elif stripped.startswith("angle_style"):
                        styles["angle_style"] = stripped
                    elif stripped.startswith("dihedral_style"):
                        styles["dihedral_style"] = stripped
                    elif stripped.startswith("improper_style"):
                        styles["improper_style"] = stripped
                    elif stripped.startswith("special_bonds"):
                        styles["special_bonds"] = stripped

        return styles
        
    def input_writer(self) -> None:
        """
        Write the LAMMPS input script for step-wise compression.
        Tracks the box lengths (lx, ly, lz) continuously during the entire run 
        and writes them into a single output file.

        :return: None
        """
        filename = f"input.in"
        data_path = os.path.join(self.output_dir, filename)
        nx, ny, nz = self.replicate_factors
        
        element_dict = {
            'pb': 'Pb', 'sn': 'Sn', 'cs': 'Cs', 'cu': 'Cu',
            'br': 'Br', 'cl': 'Cl', 'i': 'I',
            'c': 'C', 'n': 'N', 'o': 'O', 'h': 'H', 's': 'S'
        }
        
        element_list = []
        for entry in self.atom_types:
            gaff_type = entry.split()[1].lower()
            chosen_element = 'X' 
            for prefix, symbol in element_dict.items():
                if gaff_type.startswith(prefix):
                    chosen_element = symbol
                    break 
            element_list.append(chosen_element)
            
        element_string = " ".join(element_list)
        lines = []

        lines.append("units           real\n")
        lines.append("atom_style      full\n")
        lines.append("boundary        p p p\n\n")
        
        topo_styles = self.extract_topology_styles()
        
        if topo_styles["bond_style"]: lines.append(f"{topo_styles['bond_style']}\n")
        if topo_styles["angle_style"]: lines.append(f"{topo_styles['angle_style']}\n")
        if topo_styles["dihedral_style"]: lines.append(f"{topo_styles['dihedral_style']}\n")
        if topo_styles["improper_style"]: lines.append(f"{topo_styles['improper_style']}\n")
            
        if topo_styles["special_bonds"]:
            lines.append(f"{topo_styles['special_bonds']}\n\n")
        else:
            lines.append("special_bonds   lj 0.0 0.0 0.5 coul 0.0 0.0 0.83333333\n\n")
            
        lines.append(f"read_data       data_{self.cif_name}.txt\n")
        lines.append(f"replicate       {nx} {ny} {nz}\n\n")

        lines.append("pair_style      hybrid lj/cut/coul/long 9.0 buck/coul/long 9.0\n")
        lines.append("pair_modify     mix arithmetic\n")
        lines.append("pair_modify     tail yes\n")
        lines.append("kspace_style    pppm 1.0e-4\n\n")

        lines.append(f"include         coeffs_{self.cif_name}.txt\n\n")
        lines.append("timestep        1.0\n\n")
        
        lines.append("thermo_style    custom step time enthalpy etotal press temp vol lx ly lz\n")
        lines.append("thermo          500\n\n")

        lines.append("# Variables for box dimensions\n")
        lines.append("variable        lx equal lx\n")
        lines.append("variable        ly equal ly\n")
        lines.append("variable        lz equal lz\n\n")

        lines.append("# INITIAL RELAXATION TO PREVENT BOX EXPLOSIONS\n")
        lines.append("minimize        1.0e-4 1.0e-6 1000 10000\n")
        lines.append("velocity        all create 100.0 4540 mom yes dist gaussian\n\n")
        lines.append("fix             1 all nve/limit 0.1\n")
        lines.append("run             10000\n")
        lines.append("unfix           1\n")
        lines.append("reset_timestep  0\n\n")

        lines.append("# trajectory file\n")
        lines.append(f"dump            alltraj all custom 1000 {self.cif_name}_100K_all.lammpstrj id type element x y z xu yu zu vx vy vz\n")
        lines.append(f"dump_modify     alltraj element {element_string}\n\n")

        lines.append("# Continuous box size output for the entire compression process\n")
        lines.append(f"fix             box_output all ave/time 10 100 1000 v_lx v_ly v_lz file {self.cif_name}_box_compression_continuous.txt\n\n")

        pressures = [1000, 2000, 3000, 4000]
        fix_id = 2

        lines.append("# 1 atm equilibration run\n")
        lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso 1.0 1.0 1000.0\n")
        lines.append("run             80000\n")
        lines.append(f"unfix           {fix_id}\n\n")
        
        fix_id += 1
        prev_p = 1.0

        for p in pressures:
            lines.append(f"# {int(prev_p)}-{p} atm ramp\n")
            lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso {float(prev_p)} {float(p)} 1000.0\n")
            lines.append("run             30000\n")
            lines.append(f"unfix           {fix_id}\n\n")
            fix_id += 1
            
            lines.append(f"# {p} atm plateau\n")
            lines.append(f"fix             {fix_id} all npt temp 100.0 100.0 100.0 aniso {float(p)} {float(p)} 1000.0\n")
            lines.append("run             50000\n")
            lines.append(f"unfix           {fix_id}\n\n")
            fix_id += 1
            
            prev_p = p
            
        with open(data_path, "w") as file:
            file.writelines(lines)